### ISSUE TITLE
Syntax error in example

### ISSUE THREAD

**Issue by Rigwarl** [khalidhoffman/pug-bem-lexer#1]
hi, example from docs throw syntax error
```
pug.render('.block.-mod', {
  plugins : [
    lex : require('bem-pug-lexer')
  ]
});
```

```
    lex : require('bem-pug-lexer')
        ^
SyntaxError: Unexpected token :
```

if i change array to obj i get another error, how can i run it?

**Comment by khalidhoffman** [comment]
Hi @Rigwarl. I just updated the readme. It should be:
```
pug.render('.block.-mod', {
  plugins : [
    { lex : require('bem-pug-lexer') }
  ]
});
```

Thank you for bringing this to my attention!

**Comment by Rigwarl** [comment]
Thanks @khalidhoffman , but still not working for me
```
pug.render('.block.-mod', {
  plugins : [
    { lex : require('pug-bem-lexer') }
  ]
})
```
return `<div class="block -mod"></div>`
